#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

USE_PROCD=1

START=96
STOP=96
LOGFILE="/var/log/outline-gate.log"


start_service() {

        key=$(uci get routro.ireach.user)
        port=$(uci get routro.ireach.port)
        host=$(uci get routro.ireach.host)
        password=$(uci get routro.ireach.pass)

        mport=$(uci get routro.ireach.outlineport)

        oport=$(uci get routro.outlinegate.originport)
        ohost=$(uci get routro.outlinegate.originhost)


        if [ -z "$key" ] || [ -z "$port" ] || [ -z "$host" ] || [ -z "$password" ]  || [ -z "$mport" ] || [ -z "$oport" ] || [ -z "$ohost" ];then
                echo "outlineGate_status=MISSINF_CONFIG" > /tmp/outlineGate_status
                echo "Connect - service is not ready" >> $LOGFILE
                exit 0;
        fi

	procd_open_instance
	procd_set_param command /bin/sh -c "/tmp/chisel client --auth $key:$password ${host}:${port} R:0.0.0.0:$mport:$ohost:$oport >> $LOGFILE 2>&1"
    
         # Enable respawn if needed
        procd_set_param respawn

        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}

stop() {

        echo "Connect - Stopping outlinegate service" >> $LOGFILE
        # commands to kill application
}
