#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

USE_PROCD=1

START=91
STOP=91

start_service() {

	procd_open_instance
	procd_set_param command sh /usr/bin/wrong_wifi_pass_checker.sh
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop() {
        echo stop
        # commands to kill application
}